package io.sbtxx.mcdevassistant.generator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

public final class PluginGenerator {
    public void generate(String pluginName, String packageName, Path output) throws IOException {
        validate(pluginName, packageName);
        Path javaDir = output.resolve("src/main/java").resolve(packageName.replace('.', '/'));
        Path resources = output.resolve("src/main/resources");
        Files.createDirectories(javaDir);
        Files.createDirectories(resources);

        String className = toClassName(pluginName);
        Files.writeString(javaDir.resolve(className + ".java"), pluginClass(className, packageName));
        Files.writeString(resources.resolve("plugin.yml"), pluginYml(pluginName, packageName + "." + className));
        Files.writeString(output.resolve("README.md"), readme(pluginName));
    }

    private void validate(String pluginName, String packageName) {
        if (!pluginName.matches("[A-Za-z][A-Za-z0-9_-]{1,49}")) throw new IllegalArgumentException("Plugin name must be 2-50 letters/numbers/_/-.");
        if (!packageName.matches("[a-zA-Z_][a-zA-Z0-9_]*(\\.[a-zA-Z_][a-zA-Z0-9_]*)*")) throw new IllegalArgumentException("Invalid Java package: " + packageName);
    }

    private String toClassName(String name) {
        String[] parts = name.split("[-_ ]+");
        StringBuilder out = new StringBuilder();
        for (String part : parts) if (!part.isBlank()) out.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));
        return out + "Plugin";
    }

    private String pluginClass(String className, String packageName) {
        return "package " + packageName + ";\n\n"
                + "import org.bukkit.plugin.java.JavaPlugin;\n\n"
                + "public final class " + className + " extends JavaPlugin {\n"
                + "    @Override\n"
                + "    public void onEnable() {\n"
                + "        getLogger().info(\"Plugin enabled.\");\n"
                + "    }\n\n"
                + "    @Override\n"
                + "    public void onDisable() {\n"
                + "        getLogger().info(\"Plugin disabled.\");\n"
                + "    }\n"
                + "}\n";
    }

    private String pluginYml(String pluginName, String mainClass) {
        return "name: " + pluginName + "\n"
                + "version: 0.1.0\n"
                + "main: " + mainClass + "\n"
                + "api-version: '1.21'\n";
    }

    private String readme(String pluginName) {
        return "# " + pluginName + "\n\n"
                + "Generated by Minecraft Developer Assistant.\n\n"
                + "## Next steps\n"
                + "1. Add the correct server API dependency for your target platform/version.\n"
                + "2. Implement commands, events, permissions, and configuration.\n"
                + "3. Run `mcdev analyze .` to inspect the project.\n";
    }
}
